export {
  confirmPasswordReset,
  generateOTP,
  getClientPortalDetails,
  getProjectFiles,
  getProjectImages,
  getProjectStatus,
  getVendorTaskMedia,
  getVendorTasks,
  loginClient,
  registerLead,
  requestPasswordResetOtp,
  sendOtp,
  verifyPasswordResetOtp,
  type ClientPortalResponse,
  type ForgotPasswordResponse,
  type LoginClientResponse,
  type PaymentTerm,
  type PortalClientRecord,
  type PortalProject,
  type ProjectFile,
  type ProjectImage,
  type ProjectStatusRecord,
  type ProjectVendor,
  type ProjectVendorTask,
  type VendorTaskMediaItem,
} from './services/salesforceApi'
